#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias obey="cd ~/Projects/External/Obey/Code"
alias v="vim"
alias be="bundle exec"
alias pjs="cd ~/Projects"
alias vag="vagrant"
